### ISSUE TITLE
Question: Lazy Effect?

### ISSUE THREAD

**Issue by DeForce** [vobyjs/oby#6]
Is it possible for an effect to not trigger initially?

```ts
const test = $(false)

$.effect(() => {
    console.log('update', test())
})

SetTimeout(() => test(true), 100)
```

would log `test` two times.
It would be nice if we could have a flag to "not trigger on effect creation", and monitor only future changes.

Or am I blind and there is a config value that can make that possible already?

**Comment by fabiospampinato** [comment]
It's not possible to not call the effect initially, because if it's not called initially then it doesn't depend on any signals, and if it doesn't depend on any signals then when are we are ever going to call it?

**Comment by fabiospampinato** [comment]
It's not possible to not call the effect initially, because if it's not called initially then it doesn't depend on any signals, and if it doesn't depend on any signals then when are we are ever going to call it?


The trick is to always execute the part that reads signals, but only execute the part that does something with them some times. I use this little function myself, it will need adapting but it should give you the general idea:

```ts
import {$} from 'oby';

const useUpdateEffect = <T> ( subscriptions: () => void, callback: Callback ): Disposer => {

  let inited = false;

  return $.effect ( () => {

    subscriptions ();

    if ( inited ) {

      $.untrack ( callback );

    } else {

      inited = true;

    }

  });

};
```
